spring:
  application:
    name: product
  profiles:
    active: peer1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/
    # 实例信息初始化到服务器时间间隔
    initial-instance-info-replication-interval-seconds: 10