spring:
  application:
    name: zuul
  profiles:
    active: peer1
    # Redis配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis密码
    password: 123456
    # Jedis客户端
    jedis:
      # 连接池配置
      pool:
        # 最大活动连接数
        max-active: 20
        # 最大等待时间（单位毫秒）
        max-wait: 2000
        # 最小闲置连接数
        min-idle: 5
        # 最大闲置连接数
        max-idle: 15

# 向端口为5001和5002的Eureka服务治理中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka, http://localhost:5002/eureka

# Zuul的配置
zuul:
  # 禁用过滤器ValidateCodeFilter ①
  ValidateCodeFilter:
    pre:
      disable: true
  ratelimit: # ②
    # 使用Redis缓存对应的度量数据
    repository: REDIS # ③
    # 是否启用限速配置，默认为false，不启用
    enabled: true # ④
    # 默认全局配置
    default-policy-list: # ⑤
      # 时间戳内限制请求次数
      - limit: 5
        # 每次刷新间隔窗口请求时间限制（单位秒）
        quota: 10
        # 时间戳（单位秒）
        refresh-interval: 10
    policy-list: # 自定义配置 ⑥
      user-service: # 对应zuul.routes.<key>配置项 ⑦
        # 时间戳内限制请求次数
        - limit: 3
          # 每次刷新间隔窗口请求时间限制（单位秒）
          quota: 3
          # 时间窗口刷新间隔，单位秒
          refresh-interval: 5
  # 路由配置
  routes:
    # 用户微服务
    user-service: # ⑧
      # 请求拦截路径配置（使用ANT风格）
      path: /u/**
      # 通过一个URL配置
      # url: http://localhost:6001/
      # 通过服务名称配置
      service-id: user
    # 产品微服务配置
    fund-service:
      # 请求拦截路径配置（使用ANT风格）
      path: /p/**
      service-id: product