# 1.git方式
#spring:
#  cloud:
#    config:
#      # Config服务端配置
#      server:
#      # 使用Git，将从Git仓库中读取配置文件
#         git:
#          # GitHub的URI，将从GitHub
#           uri: https://github.com/zhaozuo/learn-spring-cloud-config
#          # 如果你使用的是私有仓库，则需要填写用户密码
#          # GitHub用户名
#          # username: your-username
#          # GitHub密码
#          # password: your-password
#          # 默认的Git分支，默认值为“master”
#          # default-label: master
#          # 查找路径，可以配置Git仓库的文件路径，
#          # 使用逗号分隔可配置多个路径
#          # search-paths: /config
#           skip-ssl-validation: true
#  application:
#    # 微服务名称
#    name: config-center

# 2.本地方式
#spring:
#  cloud:
#    config:
#      # Config服务端配置
#      server:
#        native:
#          # classpath指向类路径，而/configs代表目录
#          search-locations: classpath:/configs
#  application:
#    # 微服务名称
#    name: config-center
#  # 注意，这个配置项一定要配置，
#  # 否则Config服务端会因默认使用Git报错
#  profiles:
#    active: native

#3.SVN方式
spring:
  cloud:
    config:
      # Config服务端配置
      server:
        # 使用SVN
        svn: # ①
          # SVN的URI连接
          uri: https://localhost:8443/svn/chapter10/
          # 默认分支，默认值为“trunk”
          # default-label: trunk
          # SVN用户名
          username: wzz
          # SVN密码
          password: a123456789
          # SVN服务器配置文件的路径（可以多个，用逗号分隔）
          searchPaths: /config-files
  application:
    # 微服务名称
    name: config-center
  profiles:
    # 注意，这个配置项一定要配置，否则Config服务端会默认使用Git
    active: subversion # ②
## 配置端口
server:
  port: 4001